### PR TITLE
Added a lock around code generation

### PR DESCRIPTION
**Pull request by resnikb**
## Description
Code generation in Insight is not thread-safe, as `ModelBuilder` and related classes are not thread-safe, and concurrent execution can cause unpredictable results. This is one of the possible causes for recent bug reports involving missing methods in Insight-generated classes (#407 and #408)

## Checklist
Please make sure your pull request fulfills the following requirements:

- [ ] Tests for any changes have been added (for bug fixes / features).
- [ ] Docs have been added / updated (for bug fixes / features).

N/A, as deterministic tests would be hard/impossible to create.

## Type
This pull request includes what type of changes?

- [x] Bug.
- [ ] Feature.
- [ ] Code style update (formatting, local variables).
- [ ] Refactoring (no functional changes, no api changes).
- [ ] Documentation content changes.
- [ ] Other (please describe below).

## Breaking Changes
Does this pull request introduce any breaking changes?

- [ ] Yes
- [x] No

### Any other comment

(n/a)

### CODE REVIEW

**Comment by nwpz** [comment]
Is this in the pipeline to get reviewed/merged? I have encountered the issue described in #407 and #408 and am hopeful this resolves it.

**Comment by jonwagner** [comment]
I don’t have any direct evidence that it solves the problems so I haven’t kicked off a formal build. Can you do a local build of the branch and test it? Or should I work on a teat build?

I should be able to get to a production build during the US holiday week.

On Nov 22, 2019, at 2:12 PM, nwp <notifications@github.com> wrote:

﻿

Is this in the pipeline to get reviewed/merged? I have encountered the issue described in #407<https://github.com/jonwagner/Insight.Database/issues/407> and #408<https://github.com/jonwagner/Insight.Database/issues/408> and am hopeful this resolves it.

**Comment by nwpz** [comment]
I'm trying a local build, will let you know if I see the issue with this change. It's been hard to pinpoint. I've seen this sporadically for a about a year now in both .net core 2.1 and 2.2 when using insight.database. Will let you know if i see it again with this change applied.

**Comment by resnikb** [comment]
@jonwagner This one is hard to test and verify that it relates to the reported issues. The reason I went looking for threading issues in the first place were the commonalities in the issues:

- Intermittent, usually solved by restarting service/app/website
- There is seemingly random/corrupted data (e.g. messed up/mixed type names)

This smelled of a race condition to me, so I looked at the generator code, and realised that it could be executing concurrently, which would likely have similar symptoms to the ones described, as the involved framework types are not thread-safe.

**Comment by jonwagner** [comment]
Good catch @resnikb !

* Although the _constructor/_singlethreaded constructors is a concurrent dictionary, the `ModuleBuilder` and `AssemblyBuilder` are not. It's possible/likely that there was a change in their behavior in .net core that is no longer thread-safe (they never claimed to be threadsafe).
* Those classes are only used in `InterfaceGenerator` so it's likely only to affect generated interfaces.
* If ModuleBuilder methods are writing to a thread-unsafe in-memory stream, it would arise to weird missing method/etc issues.
* I did a quick read-through of other code generation classes, and they all use DynamicMethods. Those classes are used independently.

I was a little worried about performance issues converting it to single-threaded, but it's only for interface generation. There should be minimal impact switching to single-threaded.

**Comment by jonwagner** [comment]
I think I'll go with a variant of this code. Your PR puts the lock around the construction of the objects, which will single-thread connection creation. I'll refactor that method and just put the lock around the interface generation.

**Comment by jonwagner** [comment]
This fix (with slightly better locking) is now in 6.2.11.

Thanks @resnikb

**Comment by resnikb** [comment]
@jonwagner Thanks for looking into it.

However, I think your code change is not enough. The reason is that the delegate suppied to `ConcurrentDictionary.GetOrAdd` can be called concurrently for the same type - in that case the current code will try to define the same type twice, resulting in a different exception.

This is the reason why in my PR I used double-checked locking, to ensure that generation can only run once for a given type. Also, please note that I don't have a lock around object creation, only around the call to `CreateImplementorOf` *and* `TryAdd` to ensure atomicity of the operation.

**Comment by jonwagner** [comment]
Yes, you’re right that GetOrAdd calls the delegate outside of the locks and only locks the collection at add time.

If the interface generation code is called simultaneously for the same interface, I think the worst case is that two different classes are created. What error do you see it throwing?

**Comment by resnikb** [comment]
@jonwagner Ah, true, my bad - I missed the fact that type names are generated using a guid suffix. You're right that in case of concurrent executions there won't be any exceptions, and the current code will work as expected.

The only drawback of the current implementation that I see, is the potential to generate multiple implementing types for the same interface - there could be more than two, depending on how many concurrent executions of the `GetOrAdd` delegate start before the dictionary is updated, as each thread that starts executing the delegate will create one. This may be an issue for some applications, as it can add a lot of wait time in highly concurrent scenarios. For example, with N threads executing the delegate concurrently, the last thread to enter the lock will take `N x (time to generate implementation type)` to retrieve the factory delegate.

On one hand, I agree that having more than a few threads there is an edge case, but on the other, it is relatively straightforward to prevent this behavior. What are your thoughts?

**Comment by jonwagner** [comment]
I’d rather write less locking and thread management code. Too easy to get wrong (see my first attempt...)

If we’re down to creating multiple implementation classes, only one would get used, so it’s more of a resource bloat/startup issue.

It’s probably worth putting the try/get call around it to totally eliminate that case. I’ll take a look at your commit and pull that in.

On Nov 29, 2019, at 10:24 PM, Bojan Resnik <notifications@github.com> wrote:

﻿

@jonwagner<https://github.com/jonwagner> Ah, true, my bad - I missed the fact that type names are generated using a guid suffix. You're right that in case of concurrent executions there won't be any exceptions, and the current code will work as expected.

The only drawback of the current implementation that I see, is the potential to generate multiple implementing types for the same interface - there could be more than two, depending on how many concurrent executions of the GetOrAdd delegate start before the dictionary is updated, as each thread that starts executing the delegate will create one. This may be an issue for some applications, as it can add a lot of wait time in highly concurrent scenarios. For example, with N threads executing the delegate concurrently, the last thread to enter the lock will take N x (time to generate implementation type) to retrieve the factory delegate.

On one hand, I agree that having more than a few threads there is an edge case, but on the other, it is relatively straightforward to prevent this behavior. What are your thoughts?

**Pull request closed without merging**
