### PR TITLE
Workaround for VS2015 debugger compatibility

### PR DESCRIPTION
**Pull request by shaxxx**
Workaround for https://github.com/jonwagner/Insight.Database/issues/224
Added two lines to 

- InterfaceGenerator.cs @ line 64
- StaticFieldStorage.cs @ line 38

Rest is just a VS tab padding, no real changes.

### CODE REVIEW

**Comment by kevinsea** [comment]
I merged this locally and ran all of the unit tests.  It solves the debugger problem., but renaming the assembly results in unit test errors like this:

> Insight.Tests.InterfaceTests+IHaveStructure is inaccessible to Insight.Database. Make sure that the interface is public, or add [assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Insight.Database")] to your assembly.

The test projects, like some production projects, use InternalsVisibleTo("Insight.Database") to allow Insight to access non public members.

I see 2 options:
1.  Keep using the workaround mentioned in #224 for now.  Introduce the breaking change in the next major version noting that wherever you find InternalsVisibleTo("Insight.Database") you need to add InternalsVisibleTo("Insight.Database.Dynamic").
2.  Provide a method you can call at application start that would optionally add '.Dynamic' to the dynamically created assembly's name.

Side note: when either of these is adopted, the exception text above needs to be revised as well.

**Comment by AndrewFreese** [comment]
Not trying to be argumentative (just ignorant): what sensible use is there for a real (non-test) project to do weird stuff like InternalsVisibleTo?
Though I'm ignorant, I'm anxious for shaxxx's patch to make it in to a version I can use - and it seems like it might be reasonable to regard the InternalsVisibleTo changes as non-breaking.

**Comment by kevinsea** [comment]
You don't need to apologize for asking for context :)  

At an object level, Insight can access non public properties without any help.  But if you are using the [Automatic Interface Implementation](https://github.com/jonwagner/Insight.Database/wiki/Auto-Interface-Implementation) (interfaces or abstract classes), its reasonable to mark those class internal, right?  Actually, I just saw that using InternalsVisibleTo is even mentioned in that link.  

I really want to get a fix out there too.  The workaround in #224 works well, but its a hassle for everyone out there working with Insight.  Your question got me thinking, @shaxxx submitted 2 changes, one for interfaces and one for properties/fields.  We only need the fix for the latter to make the debugger happy and that code is not what needs the special access.  I tried applying the change to just the property/field generator.  The unit tests say that is a non breaking change.  I don't enough enough to say what the best approach is, we really need Jon's thoughts on this.

**Comment by shaxxx** [comment]
Nice catch @kevinsea 
As seen in the original issue I was testing with only StaticFieldStorage patch since I don't use Automatic Interface Implementation. If tests run without issues, and debugger is working I believe we have a winner here. Leave InterfaceGenerator as is and patch StaticFieldStorage.

However, I don't think we should wait for a next major release for this. Two reasons for that:
- AFAIK @jonwagner wrote that this issue is probably already fixed in next version 6 but not pushed. That's why I wanted to hear his opinion on this, but it's been a time.
- Most of the people these days use VS2015 (being free is one of the reasons). Once they try Insight and see that debugger is not working they'll simply conclude that it's not for them, and look for something better. Most of them will not found workaround (which I believe is the best solution in the end).

**Comment by kevinsea** [comment]
I think there are two separate questions:
1) How soon should we fixed it?  I agree it should be soon for the reason you mention.

2) What is the proper version number?  This is not a statement on timing, its just protecting people who rely on nuget providers following semantic versioning (http://semver.org/). I think Jon can best speak to what's customary for Insight...this is me thinking out loud and probably a source of confusion.

**Comment by jonwagner** [comment]
I try to follow semver mostly:

- Breaking fixes and big changes => major version
- Feature additions => minor version
- Bug fixes => build number

We'll get this fix in as far back as we can go without unintentionally breaking people.

There is a use case where you want to read immutable objects from the database:

    class Foo { public int X { get; } }

Then insight needs internal access. It all depends on how clean you like your objects.

**Comment by shaxxx** [comment]
Awesome! Thanks guys!

**Comment by kevinsea** [comment]
Closing because it is being replaced by #272

**Pull request closed without merging**
