### PR TITLE
Use cmd argument instead of command in closure

### PR DESCRIPTION
**Pull request by joeshifflett**
Using command in closure causes a ConnectionString missing exception on second run when using dynamic class generator.

### CODE REVIEW

**Comment by jonwagner** [comment]
Thanks, Joe.

Can you provide a snippet of code that repros the problem, so I can turn it into a test case?

**Comment by joeshifflett** [comment]
This runs fine the first time.  On the second call, an exception is thrown when the call is make to conn.CreateCommand.

using (var conn = new SqlConnection("..."))
{
	conn.Open();
	var parameters = new Dictionary<string, object>(StringComparer.InvariantCultureIgnoreCase);                    
	parameters.Add("Languages", new List<Language> {new Language {PersonId = 1047024, IsPrimary = true, LanguageId = 1714}});			
	var cmd = conn.CreateCommand("[savePersonLanguages]", parameters);
	cmd.ExecuteNonQuery();                 
}

**Comment by jonwagner** [comment]
Interesting. I wasn't able to reproduce a connection error, but I did notice that list parameters weren't copied to the resulting connection. I pushed up a fix to that in master.

Take a look at that code and see if I reproduced your test case properly.

**Comment by jonwagner** [comment]
Got it. Posting a fix.

**Comment by jonwagner** [comment]
This is fixed in master, and should be in the next build after v5.2.3

**Pull request closed without merging**
