### PR TITLE
Child list will not map to a parent with a nullable ID (Issue 265)

### PR DESCRIPTION
**Pull request by thespatt**

### CODE REVIEW

**Comment by kevinsea** [comment]
Some initial feedback:

1. Can you install VS extension EditorConfig?  This will ensure the edits match the projects whitespace etc. to avoid future merge conflicts and make the changes apparent.

1. In the code below the method name ConvertNullableID misrepresents what the method is doing,  Its converting all value types - not just nullables.

 +            if (_idType != typeof(object))
 +                convertID = ConvertNullableID<TId>;
 +            else
 +                convertID = (object id) => (TId)id;

You could call it ConvertValueToParentType().  But I think instead you should include the object line (convertID = (object id) => (TId)id;) in your method too and the method could be ConvertToParentType().  I think this is better as it seems complete and the right thing to unit test.

**Comment by jonwagner** [comment]
Yes, please. I can't review code with so much whitespace change.

And yes, just wait until the StyleCop bites. :)

**Comment by thespatt** [comment]
Thanks for the feedback guys.  I have updated the changes to minimize the whitespace issues.  The test file had some whacky whitespace, hope those changes are ok.

**Comment by jonwagner** [comment]
When I looked carefully at the code, I realized that the type mapping was old code. The generic method ensures that the types match. So in 5.2.8, I removed the type mapping code and tests pass. Cross your fingers.

**Pull request merged**
