### PR TITLE
DbType override to override default of NVarChar and use VarChar type

### PR DESCRIPTION
**Pull request by ghost1face**
* Added IParameterDataTypeMapper
* Added Unit Tests
* 100% pass

### CODE REVIEW

**Comment by ghost1face** [comment]
Good afternoon, just checking in to see if this is a viable solution.  Open to any suggestions, changes or updates.

**Comment by jonwagner** [comment]
I haven't had time to go through this yet, but I expect to make a pass through the open issues this week.

**Comment by jonwagner** [comment]
Finally getting time to look at this. I like the approach. I have to check the place you added DbType.AnsiString. Hang on...

**Comment by jonwagner** [comment]
This will be in the 6.2 build, which I'm targeting for next week.

**Pull request merged**
